name: Uptime Check

# on:
#   schedule:
#     - cron: "*/5 * * * *"
#   workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Uptime-Pulse Health Check
        run: |
          curl -X GET "https://${{ secrets.APP_DOMAIN }}/api/check" \
          -H "Authorization: Bearer ${{ secrets.API_SECRET }}"
